# Generated by Django 5.0.6 on 2024-06-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_uthors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uthors',
            new_name='authors',
        ),
    ]
